version: '3'
services:
  web:
    build: .
    depends_on:
      - mongo
    volumes:
      - .:/home/app/reach
      - /home/app/reach/node_modules
      - /home/app/reach/dist
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb://mongo/reach
      - SESSION_SECRET=${SESSION_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
  mongo:
    image: mongo:3
    ports:
      - 27017:27017
